export const SET_AUTOMATIONS_DATA = 'AUTOMATIONS/SET_AUTOMATIONS_DATA';
export const SET_AUTOMATIONS_MESSAGE = 'AUTOMATIONS/SET_MESSAGE';
export const REMOVE_AUTOMATIONS_MESSAGE = 'AUTOMATIONS/REMOVE_MESSAGE';
