export const SET_SEED_DATA = 'UTILS/SET_SEED_DATA';
export const SET_MAINTENANCE_DATA = 'UTILS/SET_MAINTENANCE_DATA';
export const SET_COLOR_DATA = 'UTILS/SET_COLOR_DATA';
export const SET_SEEDTYPE_DATA = 'UTILS/SET_SEEDTYPE_DATA';
export const SET_XERO_CONTACT_DATA = 'UTILS/SET_XERO_CONTACT_DATA';
export const SET_XERO_ACCOUNT_DATA = 'UTILS/SET_XERO_ACCOUNT_DATA';
