export const SET_FARMS_DATA = 'FARMS/SET_FARMS_DATA';
export const SET_LINE_DATA = 'FARMS/SET_LINE_DATA';
export const EDIT_NAME_GROUP = 'FARMS/EDIT_NAME_GROUP';
export const SET_ID_DELETE_ITEM = 'FARMS/SET_ID_DELETE_ITEM';
export const ON_FEEDBACK = 'FARMS/ON_FEEDBACK';
export const HIDE_MESSAGE = 'FARMS/HIDE_MESSAGE';
